VDMS 2.2 Release
IntelLabs/vdms pull request #142
Opened 2022-01-12 18:39 UTC by omp87

Updating VDMS to add auto-deletion capabilities, ability to perform custom functions when ingesting images, internal retries,

2022-01-27 16:53 UTC, cwlacewe requested changes

2022-01-27 16:53 UTC, cwlacewe commented on utils/include/comm/Connection.h
> +    const unsigned MAX_BUFFER_SIZE  = (1024*1024*1024);  // 256MB for ATTD & 1GB Video Curation
Could you remove these comment?
```suggestion
    const unsigned MAX_BUFFER_SIZE  = (1024*1024*1024);
```

2022-01-27 20:21 UTC, cwlacewe approved these changes

2022-01-28 20:22 UTC, Ragaad approved these changes

2022-01-28 22:11 UTC, merged